# Generated by Django 5.0.6 on 2024-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='avatar-1.jpg', upload_to='profile_images'),
        ),
    ]
